### ISSUE TITLE
Infinite login loop in Ubuntu after Nvidia driver installation 

### ISSUE THREAD

**Issue by srinivasgln** [NVIDIA/nvidia-installer#14]
Previously I was running Nvidia 418 with cuda 10.1 which was working fine and I can able to run tensorflow 1.15 in gpu. Recently, I inadvertently updated the driver to Nvidia 450, and tensorflow ended up not recognizing the GPU , which resulted in training my ML models in CPU. To address this problem, I tried installing Nvidia 418 again and ended up in an infinite login loop. To resolve this, thus far I have tried changing the permissions of .Xauthority (such as chown user:user .Xauthority and chmod /tmp) , purged and tried numerous NVidia drivers (even sudo ubuntu-drivers autoinstall ) , created new users but just could not able to log in.

I have attached my configurations and log reports here : My laptop configuration given in the [here](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/laptop-config.txt), My xorg, grub and other configurations are given in this [file](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/nvidia-july24th.txt) (created using man script in recovery shell)

I cannot start ‘startx’ as well…I’ve attached the log files such as [nvidia-bug-report.log.gz](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/nvidia-bug-report.log.gz), [nvidia-installer.log](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/nvidia-installer.log), [Xorg.0.log](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/Xorg.0.log), [Xorg.1.log](https://github.com/srinivasgln/nvidia-errors-srini/blob/master/Xorg.1.log). Please let me know how to resolve this issue. Thanks.

**Comment by aaronp24** [comment]
From your bug report log, your X logs are all still using the 418 driver, but there are numerous driver version mismatch errors in your system log:
```
Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: API mismatch: the client has the version 430.64, but
Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: this kernel module has the version 450.51.05.  Please
Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: make sure that this kernel module and all NVIDIA driver
Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: components have the same version.
```
This kind of mismatch likely comes from having a combination of NVIDIA driver packages from your Ubuntu distribution and the driver from the .run package installed at the same time. Please uninstall the driver with `sudo nvidia-uninstall`, purge all driver-related Ubuntu packages, and then install the driver again using only one method.

There are also a lot of Intel-related crashes in your X log, which could also explain the login loop problem you're seeing:
```
[    45.819] (II) intel(0): resizing framebuffer to 864x486
[    45.820] (II) intel(0): switch to mode 864x486@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none
[    47.927] (EE) 
[    47.927] (EE) Backtrace:
[    47.927] (EE) 0: /usr/lib/xorg/Xorg (xorg_backtrace+0x4e) [0x5577d9a8e6ce]
[    47.927] (EE) 1: /usr/lib/xorg/Xorg (0x5577d98dc000+0x1b6a69) [0x5577d9a92a69]
[    47.927] (EE) 2: /lib/x86_64-linux-gnu/libc.so.6 (0x7f35c95c8000+0x354c0) [0x7f35c95fd4c0]
[    47.927] (EE) 3: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x75dad) [0x7f35c6cc3dad]
[    47.927] (EE) 4: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x40d4c) [0x7f35c6c8ed4c]
[    47.927] (EE) 5: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x42cc1) [0x7f35c6c90cc1]
[    47.927] (EE) 6: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x46179) [0x7f35c6c94179]
[    47.927] (EE) 7: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x4968e) [0x7f35c6c9768e]
[    47.927] (EE) 8: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x3a13f) [0x7f35c6c8813f]
[    47.927] (EE) 9: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x3a342) [0x7f35c6c88342]
[    47.927] (EE) 10: /usr/lib/xorg/Xorg (0x5577d98dc000+0x13d341) [0x5577d9a19341]
[    47.927] (EE) 11: /usr/lib/xorg/Xorg (0x5577d98dc000+0x4fd47) [0x5577d992bd47]
[    47.927] (EE) 12: /usr/lib/xorg/Xorg (0x5577d98dc000+0x53d9f) [0x5577d992fd9f]
[    47.927] (EE) 13: /usr/lib/xorg/Xorg (0x5577d98dc000+0x57e13) [0x5577d9933e13]
[    47.927] (EE) 14: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf0) [0x7f35c95e8840]
[    47.927] (EE) 15: /usr/lib/xorg/Xorg (_start+0x29) [0x5577d991e069]
```

**Comment by srinivasgln** [comment]
> From your bug report log, your X logs are all still using the 418 driver, but there are numerous driver version mismatch errors in your system log:
> 
> ```
> Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: API mismatch: the client has the version 430.64, but
> Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: this kernel module has the version 450.51.05.  Please
> Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: make sure that this kernel module and all NVIDIA driver
> Jul 23 17:07:58 srini-Precision-7530 kernel: [  650.996340] NVRM: components have the same version.
> ```
> 
> This kind of mismatch likely comes from having a combination of NVIDIA driver packages from your Ubuntu distribution and the driver from the .run package installed at the same time. Please uninstall the driver with `sudo nvidia-uninstall`, purge all driver-related Ubuntu packages, and then install the driver again using only one method.
> 
> There are also a lot of Intel-related crashes in your X log, which could also explain the login loop problem you're seeing:
> 
> ```
> [    45.819] (II) intel(0): resizing framebuffer to 864x486
> [    45.820] (II) intel(0): switch to mode 864x486@60.0 on eDP1 using pipe 0, position (0, 0), rotation normal, reflection none
> [    47.927] (EE) 
> [    47.927] (EE) Backtrace:
> [    47.927] (EE) 0: /usr/lib/xorg/Xorg (xorg_backtrace+0x4e) [0x5577d9a8e6ce]
> [    47.927] (EE) 1: /usr/lib/xorg/Xorg (0x5577d98dc000+0x1b6a69) [0x5577d9a92a69]
> [    47.927] (EE) 2: /lib/x86_64-linux-gnu/libc.so.6 (0x7f35c95c8000+0x354c0) [0x7f35c95fd4c0]
> [    47.927] (EE) 3: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x75dad) [0x7f35c6cc3dad]
> [    47.927] (EE) 4: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x40d4c) [0x7f35c6c8ed4c]
> [    47.927] (EE) 5: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x42cc1) [0x7f35c6c90cc1]
> [    47.927] (EE) 6: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x46179) [0x7f35c6c94179]
> [    47.927] (EE) 7: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x4968e) [0x7f35c6c9768e]
> [    47.927] (EE) 8: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x3a13f) [0x7f35c6c8813f]
> [    47.927] (EE) 9: /usr/lib/xorg/modules/drivers/intel_drv.so (0x7f35c6c4e000+0x3a342) [0x7f35c6c88342]
> [    47.927] (EE) 10: /usr/lib/xorg/Xorg (0x5577d98dc000+0x13d341) [0x5577d9a19341]
> [    47.927] (EE) 11: /usr/lib/xorg/Xorg (0x5577d98dc000+0x4fd47) [0x5577d992bd47]
> [    47.927] (EE) 12: /usr/lib/xorg/Xorg (0x5577d98dc000+0x53d9f) [0x5577d992fd9f]
> [    47.927] (EE) 13: /usr/lib/xorg/Xorg (0x5577d98dc000+0x57e13) [0x5577d9933e13]
> [    47.927] (EE) 14: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf0) [0x7f35c95e8840]
> [    47.927] (EE) 15: /usr/lib/xorg/Xorg (_start+0x29) [0x5577d991e069]
> ```

Hi @aaronp24 , Thanks for your prompt suggestion. Based on your inputs, I tried the following in recovery shell,

1. Cannot use nvidia-uninstall , so instead tried to remove the directories
`/usr/local/cuda-10.1`
`/usr/local/cuda-10.2`
`/home/srini/NVIDIA_CUDA-10.1_Samples`
`/home/srini/NVIDIA_CUDA-10.2_Samples`

2. In addition, I purged the nvidia and cuda using 
`sudo apt-get remove --purge 'nvidia-*'`
`sudo apt-get remove --purge 'cuda-*' `

3. Then, I installed the nvidia-418 using,
`apt-get install nvidia-418`

After reboot, I no longer could see my login screen, but instead noticed a strange blinking screen that displayed this message intermittently.  

These are the new logs that I obtained after the reboot. 
![IMG_20200725_020657](https://user-images.githubusercontent.com/33199958/88423397-4cbcbe00-ce1e-11ea-9cca-7174204728d6.jpg)

[nvidia-bug-report.log.old.gz](https://github.com/NVIDIA/nvidia-installer/files/4973751/nvidia-bug-report.log.old.gz)
[Xorg.0.log](https://github.com/NVIDIA/nvidia-installer/files/4973753/Xorg.0.log)
[Xorg.1.log](https://github.com/NVIDIA/nvidia-installer/files/4973754/Xorg.1.log)
[nvidia-bug-report.log.gz](https://github.com/NVIDIA/nvidia-installer/files/4973755/nvidia-bug-report.log.gz)

Do you have any other suggestions to proceed further? Thanks.

**Comment by aaronp24** [comment]
Your Xorg.0.log still shows the server crashing in the Intel driver, and it doesn't show an NVIDIA screen being initialized at all. Xorg.1.log seems to be starting successfully on Intel, but also isn't loading the NVIDIA driver at all.

It seems like your system has configuration issues beyond what nvidia-installer is responsible for, so I'll close this issue. I would recommend getting help with your Intel setup before trying to add the NVIDIA drivers.
